### ISSUE TITLE
[CREDENTIAL] TODO

### ISSUE THREAD

**Issue by nhne** [hw5773/privacy_guardian#17]
- [x] 루트 인증서 생성 및 설치  

- [x] 위조 인증서 생성

- [ ] 캐시 
- [ ] 언인스톨시 인증서 제거

**Comment by nhne** [comment]
아무래도 shared preference 써야할듯 ㅠ
